branch-defaults:
  default:
    environment: test1-env
  master:
    environment: test3-env
    group_suffix: null
deploy:
  artifact: null
environment-defaults:
  test-env:
    branch: null
    repository: null
  test3-env:
    branch: null
    repository: null
global:
  application_name: test2
  branch: null
  default_ec2_keyname: work
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Tomcat 8.5 with Java
    8 running on 64bit Amazon Linux/3.0.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
