version: 0.2
phases:
    install:
        commands:
        - cp /cd/settings.xml /root/.m2/settings.xml
    pre_build:
        commands:
    build:
        commands:
    post_build:
        commands:
            - mvn package
            - ls /root/.m2/repository/org/camunda/bpm/camunda-distro/7.10.0/
artifacts:
    files:
        - '**/*'
    base-directory: 'target/camunda-beanstalk-1.0-SNAPSHOT-zip'