version: 0.2
phases:
    install:
        commands:
    pre_build:
        commands:
            - mkdir -p /root/.m2/repository/org/camunda/bpm/camunda-distro/7.10.0/
            - curl -o /root/.m2/repository/org/camunda/bpm/camunda-distro/7.10.0/camunda-distro-7.10.0.zip https://s3.us-east-2.amazonaws.com/camunda.distro/camunda-distro-7.10.0.zip
    build:
        commands:
    post_build:
        commands:
            - mvn package
artifacts:
    files:
        - '**/*'
    base-directory: 'camunda*'
    discard-paths: yes