version: 0.2
phases:
    install:
        commands:
    pre_build:
        commands:
    build:
        commands:
            - mvn clean install
    post_build:
        commands:
            - mvn package
artifacts:
    files:
        - '**/*'
    base-directory: 'target/camunda-beanstalk-1.0-SNAPSHOT-zip'