version: 0.2
phases:
    install:
        commands:
            - cp ./cd/settings.xml /root/.m2/settings.xml
    pre_build:
        commands:
    build:
        commands:
            - mvn clean install
    post_build:
        commands:
artifacts:
    files:
        - '**/*'
    base-directory: target/${project.artifactId}-${project.version}
cache:
  paths:
    - '/root/.m2/**/*'