version: 0.2
phases:
    install:
        commands:
    pre_build:
        commands:
            - ls /root/.m2/repository/org/camunda/bpm/camunda-distro/7.10.0/
    build:
        commands:
    post_build:
        commands:
            - ls /root/.m2/repository/org/camunda/bpm/camunda-distro/7.10.0/
            - mvn package
artifacts:
    files:
        - '**/*'
    base-directory: 'target/camunda-beanstalk-1.0-SNAPSHOT-zip'